name:               miso-tutorial-app-server
version:            '0.1.0.0'
synopsis:           The server side of an example SPA in GHCJS + Miso.
category:           Web
license:            BSD3

dependencies:
- aeson
- base
- bytestring
- containers
- http-types
- lucid
- miso
- network-uri
- servant
- servant-server
- stm
- transformers
- utf8-string
- wai
- wai-logger
- warp

executables:
  miso-tutorial-app-server:
    main:           ServerMain.hs
    source-dirs:
    - ./
    - ../shared
